apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
spec:
  restartPolicy: OnFailure
  containers:
  - name: vectoradd-test
    image: ***REMOVED***.dkr.ecr.ap-northeast-2.amazonaws.com/nvidia/samples:vectoradd-cuda10.2
    resources:
      limits:
        nvidia.com/gpu: 1
